dist: trusty
sudo: false
language: php

php:
  - '7.0'
  - '7.1'
  - nightly

env:
  - DEPENDENCIES="low" INTEGRATION_TEST="enabled"
  - DEPENDENCIES="low" INTEGRATION_TEST="disabled"
  - DEPENDENCIES="stable" INTEGRATION_TEST="enabled"
  - DEPENDENCIES="stable" INTEGRATION_TEST="disabled"

before_script:
  - composer self-update
  - composer install --prefer-source
  - if [ "$DEPENDENCIES" == "stable" ]; then composer update --prefer-stable; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - if [ "$INTEGRATION_TEST" == "disabled" ]; then make quick-test; fi;
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then make integration-test; fi;

after_script:
  - make clean

cache:
  directories:
    - $HOME/.composer/cache
