dist: trusty
sudo: required
language: php

services:
  - docker

php:
  - '7.0'
  - '7.1'
  - nightly

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.13.0
  matrix:
    - DEPENDENCIES="low" INTEGRATION_TEST="enabled"
    - DEPENDENCIES="low" INTEGRATION_TEST="disabled"
    - DEPENDENCIES="stable" INTEGRATION_TEST="enabled"
    - DEPENDENCIES="stable" INTEGRATION_TEST="disabled"

allow_failure:
  - php: nightly

before_script:
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then sudo rm /usr/local/bin/docker-compose; fi;
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose; fi;
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then chmod +x docker-compose; fi;
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then sudo mv docker-compose /usr/local/bin; fi;
  - composer self-update
  - composer install --prefer-source
  - if [ "$DEPENDENCIES" == "stable" ]; then composer update --prefer-stable; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - if [ "$INTEGRATION_TEST" == "disabled" ]; then make quick-test; fi;
  - if [ "$INTEGRATION_TEST" == "enabled" ]; then make integration-test; fi;

after_script:
  - make clean

cache:
  directories:
    - $HOME/.composer/cache
